### ISSUE TITLE
Possible copy of your project

### ISSUE THREAD

**Issue by vluzrmos** [artesaos/warehouse#3]
https://github.com/Bosnadev/Repositories

**Comment by andersao** [comment]
@vluzrmos vluzrmos Yes, he was inspired in my project, and even wrote a great article about the Repository pattern. https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/

I commented on the post stating that he had been inspired by my project, he confirmed and said he would put the credits, but did :(

**Comment by vluzrmos** [comment]
@Bosnadev please...
